# Use Node.js 18 as the base image
FROM node:22.1.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the source code into the container
COPY . .

COPY .env .

# Build the Next.js app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Command to run your app using npm start
CMD ["npm", "start"]
