# Use Node.js 22.1.0 LTS as the base image
FROM node:22.1.0

RUN apt-get update && apt-get install -y build-essential

# Create a directory for the application
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY ./package.json ./package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the source code into the container
COPY . /app

# Run npm build-tsc to generate the dist folder
RUN npm run build-tsc

# Set the working directory to the dist folder
WORKDIR /app/dist

# Expose the port your app runs on
EXPOSE 8080
EXPOSE 5432

# Command to run your app using node
CMD ["node", "index.js"]
